SEED: 100
MODEL:
    ARCH: resnet18
    INPUTSHAPE: [224, 224]
TRAIN:
    EPOCHS: 100
    USE_DDP: True
    DATASET: imagenet
    BATCH_SIZE: 64 # per-gpu
    OPTIMIZER: 
        NAME: sgd
        MOMENTUM: 0.9
        WEIGHT_DECAY: 0.0001 # 1e-5
    LR_SCHEDULER:
        WARMUP_EPOCHS: 0
        WARMUP_LR: 0.0002 # 1e-4
        BASE_LR: 0.1 # 1e-2
        MIN_LR: 0.
        TYPE: cosine
    LOSS: 
        CRITERION:
            NAME: CosineSimilarity
    METER:
        NAME: average
        ACC:
            TOPK: [1, 5]
    RUNNER:
        NAME: ssl
AUG:
    TRAIN:
        HORIZONTAL_FLIP:
            PROB: 0.5
        RANDOMRESIZEDCROP:
            ENABLE: True
            SCALE: (0.08, 1.0)
            INTERPOLATION: bilinear
        NORMLIZATION:
            MEAN: [0.485, 0.456, 0.406]
            STD: [0.229, 0.224, 0.225]
    EVALUATION:
        RESIZE: 
            ENABLE: True
            SIZE: [256, 256]
        CENTERCROP: 
            ENABLE: True
        NORMLIZATION:
            MEAN: [0.485, 0.456, 0.406]
            STD: [0.229, 0.224, 0.225]
SSL:
    TYPE: BYOL
    SETTING:
        DIM: 512
        HIDDEN_DIM: 2048
        MOMENTUM: 0.99
