SEED: 100
MODEL:
    #ARCH: cifar_resnet18
    ARCH: resnet50
    #INPUTSHAPE: [32, 32]
    INPUTSHAPE: [224, 224]
    #PRETRAINED: train_log/imagenet/simsiam_imagenet_r50_imagenet_baseline/checkpoint.pth.tar 
    #PRETRAINED: train_log/imagenet/RQbyol_randombit_4_16_add_float_r18_imagenet_baseline/checkpoint.pth.tar  
    #PRETRAINED: train_log/imagenet/RQbyol_randombit_w_2_8_f_4_8_add_float_r50_imagenet_baseline/checkpoint.pth.tar   
    #PRETRAINED: train_log_NEW/resnet50_linear_eval_cifar10/checkpoint.pth.tar
    #PRETRAINED: train_log_NEW/resnet50_linear_eval_cifar10+floatloss/checkpoint.pth.tar
    #PRETRAINED: /data/train_log_NEW/resnet50_linear_eval_cifar10_simsiam/checkpoint.pth.tar
    #PRETRAINED: train_log_NEW/resnet50_linear_eval_cifar100/checkpoint.pth.tar
    #PRETRAINED: train_log_NEW/resnet50_linear_eval_cifar100_simsiam/checkpoint.pth.tar
    #PRETRAINED: /data/train_log_NEW/resnet50_linear_eval_cifar100_mocov2/checkpoint.pth.tar
    #PRETRAINED: /data/train_log_NEW/resnet50_linear_eval_cifar100_byol/checkpoint.pth.tar
    #PRETRAINED: train_log_NEW/resnet50_linear_eval_cifar100+floatloss/checkpoint.pth.tar
    #CHECKPOINT: train_log_NEW/resnet50_finetune_cifar100/checkpoint.pth.tar
    #CHECKPOINT: train_log_NEW/resnet50_finetune_cifar100_simsiam/checkpoint.pth.tar
    #CHECKPOINT: /data/train_log_NEW/resnet50_finetune_cifar10_simsiam/checkpoint.pth.tar
    #CHECKPOINT: train_log_NEW/resnet50_finetune_cifar10_1/checkpoint.pth.tar
    #CHECKPOINT:  /data/train_log_NEW/resnet50_finetune_cifar100_mocov2/checkpoint.pth.tar
    CHECKPOINT:  /data/train_log_NEW/resnet50_finetune_cifar100_byol/checkpoint.pth.tar
    NUM_CLASSES: 100
TRAIN:
    EPOCHS: 50
    USE_DDP: True
    LINEAR_EVAL: False
    WARMUP_FC: True
    DATASET: cifar100
    BATCH_SIZE: 64 # per-gpu
    OPTIMIZER: 
        NAME: sgd
        MOMENTUM: 0.9
        WEIGHT_DECAY: 0.0001 # 1e-5
    LR_SCHEDULER:
        WARMUP_EPOCHS: 0
        WARMUP_LR: 0.0002 # 1e-4
        BASE_LR: 0.001 # 1e-2 for cifar-100, 1e-3 for cifar-10
        #BASE_LR: 0.1 
        MIN_LR: 0.
        #TYPE: cosine
        TYPE: multiStep
        DECAY_RATE: 0.1
        DECAY_MILESTONES : [30, 40]
    LOSS: 
        CRITERION:
            NAME: CrossEntropy
        #REGULARIZER:
        #    NAME: PACT
        LAMBDA: 0.0001
    METER:
        NAME: ACC
        ACC:
            TOPK: [1, 5]
    RUNNER:
        NAME: default
AUG:
    TRAIN:
        HORIZONTAL_FLIP:
            PROB: 0.5
        RANDOMRESIZEDCROP:
            ENABLE: True
            SCALE: (0.08, 1.0)
            INTERPOLATION: bilinear
        NORMLIZATION:
            MEAN: [0.4914, 0.4822, 0.4465]
            STD: [0.2023, 0.1994, 0.2010]
    EVALUATION:
        RESIZE: 
            ENABLE: True
            SIZE: [224, 224]
        CENTERCROP: 
            ENABLE: False
        NORMLIZATION:
            MEAN: [0.4914, 0.4822, 0.4465]
            STD: [0.2023, 0.1994, 0.2010]
QUANT:
    TYPE: ptq
    CALIBRATION:
        TYPE: tar
        PATH: calibrations/cifar10_train_1000.tar
        SIZE: 1000
        BATCHSIZE: 128
    W:
        BIT: 3
        SYMMETRY: True
        QUANTIZER: uniform
        GRANULARITY : channelwise
        OBSERVER_METHOD:
            NAME: MINMAX
    A:
        BIT: 3
        SYMMETRY: False
        QUANTIZER: uniform
        GRANULARITY : layerwise
        OBSERVER_METHOD:
            NAME: MINMAX
    BIT_CONFIG: [{
        "conv1": {"w": 8, "a": 8},
        "layer1.0.downsample": {"a": 0},
        "layer1.0.conv3": {"a": 0},
        "layer1.1.conv3": {"a": 0},
        "layer1.2.conv3": {"a": 0},
        "layer2.0.conv3": {"a": 0},
        "layer2.0.downsample": {"a": 0},
        "layer2.1.conv3": {"a": 0},
        "layer2.2.conv3": {"a": 0},
        "layer2.3.conv3": {"a": 0},
        "layer3.0.downsample": {"a": 0},
        "layer3.0.conv3": {"a": 0},
        "layer3.1.conv3": {"a": 0},
        "layer3.2.conv3": {"a": 0},
        "layer3.3.conv3": {"a": 0},
        "layer3.4.conv3": {"a": 0},
        "layer3.5.conv3": {"a": 0},
        "layer4.0.downsample": {"a": 0},
        "layer4.0.conv3": {"a": 0},
        "layer4.1.conv3": {"a": 0},
        "layer4.2.conv3": {"a": 0},
        "fc": {"a": 0},
    }]